- name: Variable from Inventory
  hosts: TEST
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}, COMPONENT - {{ COMPONENT1 }}

- name: Variable from playbook
  hosts: TEST
  vars:
    PLAY1: example.com
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: PLAY1 - {{ PLAY1 }}, PLAY2 - {{ PLAY2 }}

- name: Variable from roles
  hosts: TEST
  roles:
    - sample

