- name: Variable from Inventory
  hosts: localhost
  connection: local
  vars:
    students: { name: Steve, course: DevOps }
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: sample.txt
        dest: /tmp/h1.txt

    - name: Copy template
      ansible.builtin.template:
        src: sample.txt.j2
        dest: /tmp/h2.txt

    - name: Copy template - with map
      ansible.builtin.template:
        src: sample1.txt.j2
        dest: /tmp/h3.txt

