- name: Variable from Inventory
  hosts: localhost
  connection: local
  vars:
    student: { name: Steve, course: DevOps }
  tasks:
    - name: Copy template - with map
      notify: Print a Message
      ansible.builtin.template:
        src: sample1.txt.j2
        dest: /tmp/h3.txt

  handlers:
    - name: Print a Message
      ansible.builtin.debug:
        msg: Yes file has been modified


